apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-controller-deployment
spec:
  selector:
    matchLabels:
      app: chaos-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-controller
    spec:
      containers:
        - name: chaos-controller
          image: uk.icr.io/ix-liberty/rhg-chaos-controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: chaos-controller-service
spec:
  selector:
    app: chaos-controller
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort